# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Bookstore App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build

  test:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Type Check
        run: npm run type-check || tsc --noEmit

      - name: Run Unit Tests with Coverage
        run: npm test -- --coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Enforce Coverage Threshold
        run: |
          threshold=80
          total=$(npx --yes json -f coverage/coverage-summary.json -e "this.total.lines.pct")
          echo "Total coverage: $total%"
          awk -v t=$threshold -v c=$total 'BEGIN { exit (c < t) ? 1 : 0 }'

  e2e:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Run Cypress E2E Tests
        run: npm run test:e2e

      - name: Upload Cypress Videos and Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/videos
            cypress/screenshots
